### ISSUE TITLE
Estrutura inicial do projeto

### ISSUE THREAD

**Issue by dpisati** [conhecertudo/conhecertudo.github.io#16]
Criar a estrutura inicial do projeto para iniciar o desenvolvimento

**Comment by dpisati** [comment]
PR in code review - https://github.com/conhecertudo/conhecertudo.github.io/pull/15

**Comment by kvnol** [comment]
@dpisati salve, camarada. perfeito, aceitei o PR sem muitas verificações pois era apenas o project boilerplate, vou aproveitar o projetopara aprender next.
